### ISSUE TITLE
Nonce reuse breaks cipher security

### ISSUE THREAD

**Issue by milapsheth** [jpopesculian/encrypted-sled#3]
For each encryption call, the cipher is being instantiated with the [same nonce](https://github.com/jpopesculian/encrypted-sled/blob/master/src/lib.rs#L136). This breaks the security of encryption schemes like ChaCha20.

A nonce is a public value that should be unique for encryption of different messages under the same key. So, it is usually randomly generated for every encryption (or incremented as a counter if a state persists between calls, or a hybrid) and stored in plaintext along with the encrypted message. Additionally, it's recommended to use an AEAD scheme that authenticates that the encrypted data was not modified. See [ChaCha20Poly1305](https://docs.rs/chacha20poly1305/0.9.0/chacha20poly1305/) for an example with recommendations mentioned in this [RFC](https://datatracker.ietf.org/doc/html/rfc8439#section-2.8). The updated design would have to pick a random nonce and store it next to the encrypted data, and use that nonce to decrypt the data later.

**Comment by tarcieri** [comment]
Hello, @RustCrypto contributor and one of the main authors of the `chacha20`, `cipher`, and `aead` crates here.

Somewhat orthogonal to the nonce reuse issue (please let me know if you'd like me to open a separate issue) for this application I would suggest switching `EncryptionCipher` from the current `C: StreamCipher + NewCipher` bounds to using [`aead::AeadInPlace`](https://docs.rs/aead/latest/aead/trait.AeadInPlace.html). The `encrypt_in_place_detached` and `decrypt_in_place_detached` methods are mostly a drop-in replacement for the `cipher` API, with two additional details:

- you will need to input a unique nonce per message (e.g. 96/192 bits). 
- it returns a "tag" value which is needed to decrypt the message (128-bits)

The nonce can be a counter (assuming you leverage sled's transactional features to ensure it's never reused) or perhaps a safer implementation is to generate a random nonce every time.

You'll need to store the nonce and tag alongside the ciphertext of the message, then input the same nonce and tag to decrypt it.

**Comment by jpopesculian** [comment]
Super interesting! I really appreciate the information, and I had some time to research block ciphers, nonces and aead etc. Sorry it took me so long to get around to it, but I should have implemented in #4 a hopefully more secure solution. If one of you guys (@tarcieri or @milapsheth) could take a look, I'd really appreciate it
