### ISSUE TITLE
Benchmark / performance numbers

### ISSUE THREAD

**Issue by joepio** [jpopesculian/encrypted-sled#5]
Hi there, thanks for creating and sharing this! Love the idea. I was wondering about the performance impact. Do you have an estimate of how encryption impacts the performance?

**Comment by jpopesculian** [comment]
Hi @joepio thats a really great question! Sorry i'm just getting around to seeing this. I have no idea, and benchmarks are notoriously difficult to get correct.... it also of course depends on which kinds of encryption you're using and on which hardware. you're going to get vastly different results if you use AES on an x86 machine that supports AES-NI vs some other AEAD backend. But of course there's always an overhead to security... If you'd like to submit some benchmarks, I'm happy to accept a PR but I think right now I'd like to focus on the security over speed and make sure the crypto's right
